chain:
  bech32_prefix: st
  modules:
    - modules
    - messages
    - auth
    - bank
    - consensus
    - gov
    - mint
    - slashing
    - staking
    - distribution
    - actions
    - pricefeed
node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://host.docker.internal:26657
      max_connections: 20
    grpc:
      address: host.docker.internal:9090
      insecure: true
parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  start_height: 1
  average_block_time: 5s
  genesis_file_path: /bdjuno/.bdjuno/genesis.json
database:
  url: "postgres://stratos:stratos@postgres:5432/stratos_db?sslmode=disable&search_path=public"
  ssl_mode_enable: false
  max_open_connections: 1
  max_idle_connections: 1
  partition_size: 100000
  partition_batch: 1000
logging:
  level: debug
  format: text
pricefeed:
  tokens:
    - name: STOS
      units:
        - denom: wei
          exponent: 0
        - denom: gwei
          exponent: 9
        - denom: stos
          exponent: 18
          price_id: stratos

actions:
  port: 5005
